// <auto-generated />
namespace TenderInfo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit29 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit29));
        
        string IMigrationMetadata.Id
        {
            get { return "201809150017465_edit29"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
